spring:
  profiles:
    active: 
      -dev
---
server:
    port: 8001
spring:
  profiles: dev
  application:
    name: cloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dome01?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package: com.itcast.model
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cloud-dept-8001
    prefer-ip-address: true

info:
  ap.name: dome-springcloud
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
    port: 8001
spring:
  profiles: test
  application:
    name: cloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dome01?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package: com.itcast.model
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cloud-dept-8001
    prefer-ip-address: true

info:
  ap.name: dome-springcloud
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---

  